name: CI Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 2.1.2
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    #FIXME: split .lock file for `win32` and `linux` platforms
    - name: Force regenerate poetry.lock
      run: |
        rm -f poetry.lock
        poetry lock

    - name: Install dependencies
      run: poetry install --no-interaction --with dev

    - name: Codestyle checks
      run: poetry run poe hard-check

    - name: Tests
      run: poetry run poe test
